# Generated by Django 4.0.4 on 2022-07-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_widget_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='db_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='widget',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
