# Generated by Django 4.0.4 on 2022-07-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_widget_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='description',
            field=models.CharField(default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='widget',
            name='quantity',
            field=models.CharField(default=2, max_length=150),
        ),
    ]
