# Generated by Django 4.0.4 on 2022-07-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_widget_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='quantity',
            field=models.CharField(max_length=150),
        ),
    ]
